export const designSystem = {
  color: {
    primary: 'var(--color-primary)',
    secondary: 'var(--color-secondary)',
    accent: 'var(--color-accent)',
    background: 'var(--color-background)',
    surface: 'var(--color-surface)',
    border: 'var(--color-border)',
    textPrimary: 'var(--color-text-primary)',
    textSecondary: 'var(--color-text-secondary)',
    success: 'var(--color-success)',
    warning: 'var(--color-warning)',
    error: 'var(--color-error)',
    info: 'var(--color-info)',
  },
  typography: {
    h1: 'var(--type-h1-size)',
    h2: 'var(--type-h2-size)',
    h3: 'var(--type-h3-size)',
    h4: 'var(--type-h4-size)',
    bodyLarge: 'var(--type-body-large-size)',
    body: 'var(--type-body-size)',
    small: 'var(--type-small-size)',
    caption: 'var(--type-caption-size)',
    button: 'var(--type-button-size)',
    placeholder: 'var(--type-placeholder-size)',
  },
  spacing: {
    4: 'var(--space-1)',
    8: 'var(--space-2)',
    12: 'var(--space-3)',
    16: 'var(--space-4)',
    20: 'var(--space-5)',
    24: 'var(--space-6)',
    32: 'var(--space-8)',
    40: 'var(--space-10)',
    48: 'var(--space-12)',
    64: 'var(--space-16)',
    80: 'var(--space-20)',
    96: 'var(--space-24)',
  },
  radius: {
    small: 'var(--radius-small)',
    medium: 'var(--radius-medium)',
    large: 'var(--radius-large)',
    xl: 'var(--radius-xl)',
  },
  shadow: {
    xs: 'var(--shadow-xs)',
    small: 'var(--shadow-sm)',
    medium: 'var(--shadow-md)',
    large: 'var(--shadow-lg)',
    xl: 'var(--shadow-xl)',
  },
  transition: {
    fast: 'var(--duration-fast)',
    standard: 'var(--duration-moderate)',
    slow: 'var(--duration-slow)',
    easing: 'var(--easing-standard)',
  },
  breakpoints: {
    compact: 380,
    mobile: 620,
    tablet: 960,
    desktop: 1120,
  },
} as const

export type DesignSystem = typeof designSystem
