type PhonePrefix = {
  country: string
  countryCode: string
  dialCode: `+${number}`
}

const countryFlag = (countryCode: string) =>
  String.fromCodePoint(
    ...countryCode.split('').map((character) => 127397 + character.charCodeAt(0)),
  )

const prefixes: PhonePrefix[] = [
  { country: 'Italia', countryCode: 'IT', dialCode: '+39' },
  { country: 'Afghanistan', countryCode: 'AF', dialCode: '+93' },
  { country: 'Albania', countryCode: 'AL', dialCode: '+355' },
  { country: 'Algeria', countryCode: 'DZ', dialCode: '+213' },
  { country: 'Andorra', countryCode: 'AD', dialCode: '+376' },
  { country: 'Angola', countryCode: 'AO', dialCode: '+244' },
  { country: 'Anguilla', countryCode: 'AI', dialCode: '+1264' },
  { country: 'Antigua e Barbuda', countryCode: 'AG', dialCode: '+1268' },
  { country: 'Arabia Saudita', countryCode: 'SA', dialCode: '+966' },
  { country: 'Argentina', countryCode: 'AR', dialCode: '+54' },
  { country: 'Armenia', countryCode: 'AM', dialCode: '+374' },
  { country: 'Aruba', countryCode: 'AW', dialCode: '+297' },
  { country: 'Australia', countryCode: 'AU', dialCode: '+61' },
  { country: 'Austria', countryCode: 'AT', dialCode: '+43' },
  { country: 'Azerbaigian', countryCode: 'AZ', dialCode: '+994' },
  { country: 'Bahamas', countryCode: 'BS', dialCode: '+1242' },
  { country: 'Bahrein', countryCode: 'BH', dialCode: '+973' },
  { country: 'Bangladesh', countryCode: 'BD', dialCode: '+880' },
  { country: 'Barbados', countryCode: 'BB', dialCode: '+1246' },
  { country: 'Belgio', countryCode: 'BE', dialCode: '+32' },
  { country: 'Belize', countryCode: 'BZ', dialCode: '+501' },
  { country: 'Benin', countryCode: 'BJ', dialCode: '+229' },
  { country: 'Bermuda', countryCode: 'BM', dialCode: '+1441' },
  { country: 'Bhutan', countryCode: 'BT', dialCode: '+975' },
  { country: 'Bielorussia', countryCode: 'BY', dialCode: '+375' },
  { country: 'Bolivia', countryCode: 'BO', dialCode: '+591' },
  { country: 'Bonaire, Sint Eustatius e Saba', countryCode: 'BQ', dialCode: '+599' },
  { country: 'Bosnia ed Erzegovina', countryCode: 'BA', dialCode: '+387' },
  { country: 'Botswana', countryCode: 'BW', dialCode: '+267' },
  { country: 'Brasile', countryCode: 'BR', dialCode: '+55' },
  { country: 'Brunei', countryCode: 'BN', dialCode: '+673' },
  { country: 'Bulgaria', countryCode: 'BG', dialCode: '+359' },
  { country: 'Burkina Faso', countryCode: 'BF', dialCode: '+226' },
  { country: 'Burundi', countryCode: 'BI', dialCode: '+257' },
  { country: 'Cambogia', countryCode: 'KH', dialCode: '+855' },
  { country: 'Camerun', countryCode: 'CM', dialCode: '+237' },
  { country: 'Canada', countryCode: 'CA', dialCode: '+1' },
  { country: 'Capo Verde', countryCode: 'CV', dialCode: '+238' },
  { country: 'Ciad', countryCode: 'TD', dialCode: '+235' },
  { country: 'Cile', countryCode: 'CL', dialCode: '+56' },
  { country: 'Cina', countryCode: 'CN', dialCode: '+86' },
  { country: 'Cipro', countryCode: 'CY', dialCode: '+357' },
  { country: 'Colombia', countryCode: 'CO', dialCode: '+57' },
  { country: 'Comore', countryCode: 'KM', dialCode: '+269' },
  { country: 'Congo', countryCode: 'CG', dialCode: '+242' },
  { country: 'Corea del Nord', countryCode: 'KP', dialCode: '+850' },
  { country: 'Corea del Sud', countryCode: 'KR', dialCode: '+82' },
  { country: 'Costa Rica', countryCode: 'CR', dialCode: '+506' },
  { country: 'Costa d’Avorio', countryCode: 'CI', dialCode: '+225' },
  { country: 'Croazia', countryCode: 'HR', dialCode: '+385' },
  { country: 'Cuba', countryCode: 'CU', dialCode: '+53' },
  { country: 'Curaçao', countryCode: 'CW', dialCode: '+599' },
  { country: 'Danimarca', countryCode: 'DK', dialCode: '+45' },
  { country: 'Dominica', countryCode: 'DM', dialCode: '+1767' },
  { country: 'Ecuador', countryCode: 'EC', dialCode: '+593' },
  { country: 'Egitto', countryCode: 'EG', dialCode: '+20' },
  { country: 'El Salvador', countryCode: 'SV', dialCode: '+503' },
  { country: 'Emirati Arabi Uniti', countryCode: 'AE', dialCode: '+971' },
  { country: 'Eritrea', countryCode: 'ER', dialCode: '+291' },
  { country: 'Estonia', countryCode: 'EE', dialCode: '+372' },
  { country: 'Eswatini', countryCode: 'SZ', dialCode: '+268' },
  { country: 'Etiopia', countryCode: 'ET', dialCode: '+251' },
  { country: 'Figi', countryCode: 'FJ', dialCode: '+679' },
  { country: 'Filippine', countryCode: 'PH', dialCode: '+63' },
  { country: 'Finlandia', countryCode: 'FI', dialCode: '+358' },
  { country: 'Francia', countryCode: 'FR', dialCode: '+33' },
  { country: 'Gabon', countryCode: 'GA', dialCode: '+241' },
  { country: 'Gambia', countryCode: 'GM', dialCode: '+220' },
  { country: 'Georgia', countryCode: 'GE', dialCode: '+995' },
  { country: 'Germania', countryCode: 'DE', dialCode: '+49' },
  { country: 'Ghana', countryCode: 'GH', dialCode: '+233' },
  { country: 'Giamaica', countryCode: 'JM', dialCode: '+1876' },
  { country: 'Giappone', countryCode: 'JP', dialCode: '+81' },
  { country: 'Gibilterra', countryCode: 'GI', dialCode: '+350' },
  { country: 'Gibuti', countryCode: 'DJ', dialCode: '+253' },
  { country: 'Giordania', countryCode: 'JO', dialCode: '+962' },
  { country: 'Grecia', countryCode: 'GR', dialCode: '+30' },
  { country: 'Grenada', countryCode: 'GD', dialCode: '+1473' },
  { country: 'Groenlandia', countryCode: 'GL', dialCode: '+299' },
  { country: 'Guadalupa', countryCode: 'GP', dialCode: '+590' },
  { country: 'Guam', countryCode: 'GU', dialCode: '+1671' },
  { country: 'Guatemala', countryCode: 'GT', dialCode: '+502' },
  { country: 'Guernsey', countryCode: 'GG', dialCode: '+44' },
  { country: 'Guinea', countryCode: 'GN', dialCode: '+224' },
  { country: 'Guinea-Bissau', countryCode: 'GW', dialCode: '+245' },
  { country: 'Guinea Equatoriale', countryCode: 'GQ', dialCode: '+240' },
  { country: 'Guyana', countryCode: 'GY', dialCode: '+592' },
  { country: 'Guyana francese', countryCode: 'GF', dialCode: '+594' },
  { country: 'Haiti', countryCode: 'HT', dialCode: '+509' },
  { country: 'Honduras', countryCode: 'HN', dialCode: '+504' },
  { country: 'Hong Kong', countryCode: 'HK', dialCode: '+852' },
  { country: 'India', countryCode: 'IN', dialCode: '+91' },
  { country: 'Indonesia', countryCode: 'ID', dialCode: '+62' },
  { country: 'Iran', countryCode: 'IR', dialCode: '+98' },
  { country: 'Iraq', countryCode: 'IQ', dialCode: '+964' },
  { country: 'Irlanda', countryCode: 'IE', dialCode: '+353' },
  { country: 'Islanda', countryCode: 'IS', dialCode: '+354' },
  { country: 'Isola di Man', countryCode: 'IM', dialCode: '+44' },
  { country: 'Isole Cayman', countryCode: 'KY', dialCode: '+1345' },
  { country: 'Isole Cook', countryCode: 'CK', dialCode: '+682' },
  { country: 'Isole Faroe', countryCode: 'FO', dialCode: '+298' },
  { country: 'Isole Falkland', countryCode: 'FK', dialCode: '+500' },
  { country: 'Isole Marshall', countryCode: 'MH', dialCode: '+692' },
  { country: 'Isole Marianne Settentrionali', countryCode: 'MP', dialCode: '+1670' },
  { country: 'Isole Salomone', countryCode: 'SB', dialCode: '+677' },
  { country: 'Isole Turks e Caicos', countryCode: 'TC', dialCode: '+1649' },
  { country: 'Isole Vergini Americane', countryCode: 'VI', dialCode: '+1340' },
  { country: 'Isole Vergini Britanniche', countryCode: 'VG', dialCode: '+1284' },
  { country: 'Israele', countryCode: 'IL', dialCode: '+972' },
  { country: 'Jersey', countryCode: 'JE', dialCode: '+44' },
  { country: 'Kazakistan', countryCode: 'KZ', dialCode: '+7' },
  { country: 'Kenya', countryCode: 'KE', dialCode: '+254' },
  { country: 'Kirghizistan', countryCode: 'KG', dialCode: '+996' },
  { country: 'Kiribati', countryCode: 'KI', dialCode: '+686' },
  { country: 'Kosovo', countryCode: 'XK', dialCode: '+383' },
  { country: 'Kuwait', countryCode: 'KW', dialCode: '+965' },
  { country: 'Laos', countryCode: 'LA', dialCode: '+856' },
  { country: 'Lesotho', countryCode: 'LS', dialCode: '+266' },
  { country: 'Lettonia', countryCode: 'LV', dialCode: '+371' },
  { country: 'Libano', countryCode: 'LB', dialCode: '+961' },
  { country: 'Liberia', countryCode: 'LR', dialCode: '+231' },
  { country: 'Libia', countryCode: 'LY', dialCode: '+218' },
  { country: 'Liechtenstein', countryCode: 'LI', dialCode: '+423' },
  { country: 'Lituania', countryCode: 'LT', dialCode: '+370' },
  { country: 'Lussemburgo', countryCode: 'LU', dialCode: '+352' },
  { country: 'Macao', countryCode: 'MO', dialCode: '+853' },
  { country: 'Macedonia del Nord', countryCode: 'MK', dialCode: '+389' },
  { country: 'Madagascar', countryCode: 'MG', dialCode: '+261' },
  { country: 'Malawi', countryCode: 'MW', dialCode: '+265' },
  { country: 'Malaysia', countryCode: 'MY', dialCode: '+60' },
  { country: 'Maldive', countryCode: 'MV', dialCode: '+960' },
  { country: 'Mali', countryCode: 'ML', dialCode: '+223' },
  { country: 'Malta', countryCode: 'MT', dialCode: '+356' },
  { country: 'Marocco', countryCode: 'MA', dialCode: '+212' },
  { country: 'Martinica', countryCode: 'MQ', dialCode: '+596' },
  { country: 'Mauritania', countryCode: 'MR', dialCode: '+222' },
  { country: 'Mauritius', countryCode: 'MU', dialCode: '+230' },
  { country: 'Mayotte', countryCode: 'YT', dialCode: '+262' },
  { country: 'Messico', countryCode: 'MX', dialCode: '+52' },
  { country: 'Micronesia', countryCode: 'FM', dialCode: '+691' },
  { country: 'Moldavia', countryCode: 'MD', dialCode: '+373' },
  { country: 'Monaco', countryCode: 'MC', dialCode: '+377' },
  { country: 'Mongolia', countryCode: 'MN', dialCode: '+976' },
  { country: 'Montenegro', countryCode: 'ME', dialCode: '+382' },
  { country: 'Montserrat', countryCode: 'MS', dialCode: '+1664' },
  { country: 'Mozambico', countryCode: 'MZ', dialCode: '+258' },
  { country: 'Myanmar', countryCode: 'MM', dialCode: '+95' },
  { country: 'Namibia', countryCode: 'NA', dialCode: '+264' },
  { country: 'Nauru', countryCode: 'NR', dialCode: '+674' },
  { country: 'Nepal', countryCode: 'NP', dialCode: '+977' },
  { country: 'Nicaragua', countryCode: 'NI', dialCode: '+505' },
  { country: 'Niger', countryCode: 'NE', dialCode: '+227' },
  { country: 'Nigeria', countryCode: 'NG', dialCode: '+234' },
  { country: 'Niue', countryCode: 'NU', dialCode: '+683' },
  { country: 'Norvegia', countryCode: 'NO', dialCode: '+47' },
  { country: 'Nuova Caledonia', countryCode: 'NC', dialCode: '+687' },
  { country: 'Nuova Zelanda', countryCode: 'NZ', dialCode: '+64' },
  { country: 'Oman', countryCode: 'OM', dialCode: '+968' },
  { country: 'Paesi Bassi', countryCode: 'NL', dialCode: '+31' },
  { country: 'Pakistan', countryCode: 'PK', dialCode: '+92' },
  { country: 'Palau', countryCode: 'PW', dialCode: '+680' },
  { country: 'Palestina', countryCode: 'PS', dialCode: '+970' },
  { country: 'Panama', countryCode: 'PA', dialCode: '+507' },
  { country: 'Papua Nuova Guinea', countryCode: 'PG', dialCode: '+675' },
  { country: 'Paraguay', countryCode: 'PY', dialCode: '+595' },
  { country: 'Perù', countryCode: 'PE', dialCode: '+51' },
  { country: 'Polinesia francese', countryCode: 'PF', dialCode: '+689' },
  { country: 'Polonia', countryCode: 'PL', dialCode: '+48' },
  { country: 'Portogallo', countryCode: 'PT', dialCode: '+351' },
  { country: 'Porto Rico', countryCode: 'PR', dialCode: '+1787' },
  { country: 'Qatar', countryCode: 'QA', dialCode: '+974' },
  { country: 'Regno Unito', countryCode: 'GB', dialCode: '+44' },
  { country: 'Repubblica Ceca', countryCode: 'CZ', dialCode: '+420' },
  { country: 'Repubblica Centrafricana', countryCode: 'CF', dialCode: '+236' },
  { country: 'Repubblica Democratica del Congo', countryCode: 'CD', dialCode: '+243' },
  { country: 'Repubblica Dominicana', countryCode: 'DO', dialCode: '+1809' },
  { country: 'Riunione', countryCode: 'RE', dialCode: '+262' },
  { country: 'Romania', countryCode: 'RO', dialCode: '+40' },
  { country: 'Ruanda', countryCode: 'RW', dialCode: '+250' },
  { country: 'Russia', countryCode: 'RU', dialCode: '+7' },
  { country: 'Sahara Occidentale', countryCode: 'EH', dialCode: '+212' },
  { country: 'Saint Kitts e Nevis', countryCode: 'KN', dialCode: '+1869' },
  { country: 'Saint Lucia', countryCode: 'LC', dialCode: '+1758' },
  { country: 'Saint Martin', countryCode: 'MF', dialCode: '+590' },
  { country: 'Saint Vincent e Grenadine', countryCode: 'VC', dialCode: '+1784' },
  { country: 'Samoa', countryCode: 'WS', dialCode: '+685' },
  { country: 'Samoa Americane', countryCode: 'AS', dialCode: '+1684' },
  { country: 'San Marino', countryCode: 'SM', dialCode: '+378' },
  { country: 'Sant’Elena', countryCode: 'SH', dialCode: '+290' },
  { country: 'São Tomé e Príncipe', countryCode: 'ST', dialCode: '+239' },
  { country: 'Senegal', countryCode: 'SN', dialCode: '+221' },
  { country: 'Serbia', countryCode: 'RS', dialCode: '+381' },
  { country: 'Seychelles', countryCode: 'SC', dialCode: '+248' },
  { country: 'Sierra Leone', countryCode: 'SL', dialCode: '+232' },
  { country: 'Singapore', countryCode: 'SG', dialCode: '+65' },
  { country: 'Sint Maarten', countryCode: 'SX', dialCode: '+1721' },
  { country: 'Siria', countryCode: 'SY', dialCode: '+963' },
  { country: 'Slovacchia', countryCode: 'SK', dialCode: '+421' },
  { country: 'Slovenia', countryCode: 'SI', dialCode: '+386' },
  { country: 'Somalia', countryCode: 'SO', dialCode: '+252' },
  { country: 'Spagna', countryCode: 'ES', dialCode: '+34' },
  { country: 'Sri Lanka', countryCode: 'LK', dialCode: '+94' },
  { country: 'Stati Uniti', countryCode: 'US', dialCode: '+1' },
  { country: 'Sudafrica', countryCode: 'ZA', dialCode: '+27' },
  { country: 'Sudan', countryCode: 'SD', dialCode: '+249' },
  { country: 'Sud Sudan', countryCode: 'SS', dialCode: '+211' },
  { country: 'Suriname', countryCode: 'SR', dialCode: '+597' },
  { country: 'Svezia', countryCode: 'SE', dialCode: '+46' },
  { country: 'Svizzera', countryCode: 'CH', dialCode: '+41' },
  { country: 'Taiwan', countryCode: 'TW', dialCode: '+886' },
  { country: 'Tagikistan', countryCode: 'TJ', dialCode: '+992' },
  { country: 'Tanzania', countryCode: 'TZ', dialCode: '+255' },
  { country: 'Thailandia', countryCode: 'TH', dialCode: '+66' },
  { country: 'Timor Est', countryCode: 'TL', dialCode: '+670' },
  { country: 'Togo', countryCode: 'TG', dialCode: '+228' },
  { country: 'Tokelau', countryCode: 'TK', dialCode: '+690' },
  { country: 'Tonga', countryCode: 'TO', dialCode: '+676' },
  { country: 'Trinidad e Tobago', countryCode: 'TT', dialCode: '+1868' },
  { country: 'Tunisia', countryCode: 'TN', dialCode: '+216' },
  { country: 'Turchia', countryCode: 'TR', dialCode: '+90' },
  { country: 'Turkmenistan', countryCode: 'TM', dialCode: '+993' },
  { country: 'Tuvalu', countryCode: 'TV', dialCode: '+688' },
  { country: 'Ucraina', countryCode: 'UA', dialCode: '+380' },
  { country: 'Uganda', countryCode: 'UG', dialCode: '+256' },
  { country: 'Ungheria', countryCode: 'HU', dialCode: '+36' },
  { country: 'Uruguay', countryCode: 'UY', dialCode: '+598' },
  { country: 'Uzbekistan', countryCode: 'UZ', dialCode: '+998' },
  { country: 'Vanuatu', countryCode: 'VU', dialCode: '+678' },
  { country: 'Vaticano', countryCode: 'VA', dialCode: '+39' },
  { country: 'Venezuela', countryCode: 'VE', dialCode: '+58' },
  { country: 'Vietnam', countryCode: 'VN', dialCode: '+84' },
  { country: 'Wallis e Futuna', countryCode: 'WF', dialCode: '+681' },
  { country: 'Yemen', countryCode: 'YE', dialCode: '+967' },
  { country: 'Zambia', countryCode: 'ZM', dialCode: '+260' },
  { country: 'Zimbabwe', countryCode: 'ZW', dialCode: '+263' },
]

export const phonePrefixOptions = prefixes.map(({ country, countryCode, dialCode }) => ({
  dialCode,
  label: `${countryFlag(countryCode)} ${dialCode} — ${country}`,
  value: countryCode,
}))
